const translation = {
  Global: {
    Continue: 'Continue',
    Back: 'Retour',
    GoBackHome: "Retour à l'accueil",
    Modify: 'Modifier',
    from: 'de',
    to: 'à',
    Yes: 'Oui',
    No: 'Non',
    Search: 'Recherche',
    Create: 'Créer',
    Cancel: 'Annuler',
    Save: 'Enregister',
    None: 'Aucun',
    Nature: 'En nature',
    Argent: 'En argent',
    Add: 'Ajouter',
    Send: 'Envoyer',
    Message: 'Message',
    ChooseImage: 'Choisir depuis la galerie',
    EmailErrorEmpty: "L'e-mail ne peut pas être vide.",
    PhoneErrorEmpty: 'Le téléphone ne peut pas être vide.',
    NameErrorEmpty: 'Le prénom et nom ne peut pas être vide.',
    NameSectionErrorEmpty: 'Nom ne peut pas être vide.',
    PasswordErrorEmpty: 'Le mot de passe ne peut pas être vide.',
    RetapePasswordErrorEmpty: 'Retaper le mot de passe ne peut pas être vide.',
    DescriptionErrorEmpty: 'Description ne peut pas être vide.',
    DeviseErrorEmpty: 'Devise ne peut pas être vide.',
    ImageErrorEmpty: 'Image ne peut pas être vide.',
    PrixUnitaireErrorEmpty: 'Prix Unitaire ne peut pas être vide.',
    LocalisationErrorEmpty: 'Emplacement ne peut pas être vide.',
    QuantiteErrorEmpty: 'Quantité ne peut pas être vide.',
    CategoryErrorEmpty: 'Categorie ne peut pas être vide.',
    OffreErrorEmpty: 'Offre ne peut pas être vide.',
    ConditionsErrorEmpty: 'Condition ne peut pas être vide.',
    EmailNotExist: 'Aucun utilisateur trouvé pour cet email',
    RestorePassword: 'Restaurer le mot de passe',
    VerifyEmail: 'Vérifier l’email',
    BackTologin: 'Retour à la page de connexion',
    EmailError: "Oups ! Nous avons besoin d'une adresse e-mail valide.",
    PhoneError: "Oups ! Nous avons besoin d'un numero de téléphone valide.",
    PasswordError:
      "Oups ! Nous avons besoin d'un mot de passe valide. Le mot de passe doit comporter au moins 8 caractères, une majuscule, une minuscule, un caractère spécial, un chiffre.",
    RetapePasswordError:
      "Oups ! Nous avons besoin d'un mot de passe valide. Le mot de passe doit comporter au moins 8 caractères, une majuscule, une minuscule, un caractère spécial, un chiffre.",
    PasswordNotConfirm: 'Oups, les deux mots de passe ne correspondent pas.',
    AccountExists: 'Cet email a déjà un compte',
    AllSelect: 'Tout sélectionner',
    Delete: 'Supprimer',
    EmptyList: 'Aucun résultat trouvé',
    OfferChoose: 'Faut choisir une offre',
    DateDGTDateF: 'Date debut ne doit être superieur à Date Fin',
    EmailExisting: "Un compte existe déjà avec cet email",
    PhoneExisting: "Un compte existe déjà avec cet numéro de téléphone",
    Resend: "Renvoyer code",
    ConfirmCode: "Confirmer code",
    Submit: "Soumettre",
    Paid: "Payer",
    Confirm: "Confirmer",
    ZoneErrorEmpty: 'Zone ne peut pas être vide.',
    ChooseImages: 'Choisir des images',
    SelectTime: "Sélectionner l'heure",
    SelectDate: "Sélectionner la date",
    ProvinceErrorEmpty: 'Province ne peut pas être vide.',
    RegionErrorEmpty: 'Region ne peut pas être vide.',
    TypePrixErrorEmpty: 'Type de Prix ne peut pas être vide.',
  },
  LoginScreen: {
    title: 'Connectez-vous',
    paragraph: 'Connectez-vous pour accéder à votre espace',
    Email: 'Email',
    Password: 'Mot de passe',
    Forgotpassword: 'Mot de passe oublié ?',
    Login: 'Se connecter',
    DontHaveAccount: 'Vous n’avez pas de compte ?',
    SignUp: "S'inscrire",
    LoginError: "Oups, L'e-mail ou/et le mot de passe sont erronés",
    LoginActifError: 'Oups, Ce compte avec cet email/mot de passe est désactivé',
  },
  RegisterScreen: {
    title: 'Créer un compte',
    paragraph: 'S’inscrire pour accéder à votre espace',
    Name: 'Prénoms et Nom',
    Email: 'Email',
    Phone: 'Téléphone',
    Password: 'Mot de passe',
    RetapePassword: 'Re-taper le mot de passe',
    Login: 'Se connecter',
    AlreadyHaveAccount: 'Vous avez déjà un compte ?',
    SignUp: "S'inscrire",
  },
  Screens: {
    Home: 'Accueil',
    Events: 'Evénements',
    Invitations: 'Invitations',
    Contributions: 'Contributions',
    Achats: 'Acheter',
    Settings: 'Plus',
  },
  HomeScreen: {
    title: 'Page d’accueil',
  },
  AccueilList: {
    Evenements: 'Evénements',
    Invitations: 'Invitations',
    Contributions: 'Contributions',
    Ventes: 'Devenir Vendeur',
    Achats: 'Acheter',
  },
  Events: {
    title: 'Evénements',
    EmptyList: 'Aucun événement pour le moment',
    AddButtonText: 'Créer un événement',
    addToCalendar: 'Ajouter au calendrier',
    Invite: 'Inviter',
    Invited: 'Invité',
    Maybe: 'Peut être',
    AmountDonation: 'Montant total',
    CloseDonation: 'Fermer la contribution',
  },
  AddEvent: {
    title: 'Créer un événement',
    Name: "Nom de l'événement",
    Description: 'Description',
    DateHeure: "Date et l'heure",
    DateDebut: 'Date de début',
    DateFin: 'Date de fin',
    Emplacement: 'Emplacement',
    CharacterCount: 'caractères',
    titleModify: 'Modifier un événement',
  },
  InvitationsContacts: {
    title: 'Invitez vos contacts',
    Share: 'Partage',
    Everyone: 'Tout le monde avec le lien',
    Limit: '+1 Limite',
    Nos: 'Pas de +1',
    Invite: 'Inviter un nouvel utilisateur',
    FromContacts: 'À partir des contacts',
    PhoneNumber: 'Numéro de téléphone',
    Invitee: 'Inviter',
  },
  Invitations: {
    title: 'Invitations',
    EmptyList: 'Aucune invitation pour le moment',
  },
  InvitationsDetails: {
    title: 'Détails des invitations',
    Presence: "Présence à l'événement ?",
    nbrPersons: 'Nombre de personnes présentes',
    Adults: 'Adultes',
    KidsOver17: 'Enfants de 0 à 17 ans',
    KidsAge: "Âge de l'enfant",
  },
  Contributions: {
    title: 'Contributions',
    EmptyList: 'Aucune invitation au don pour le moment',
  },
  ContributionsDetails: {
    title: 'Faire un don',
    Contribution: 'Vous souhaitez contribuer à cet événement ?',
    Nature: 'Type de contribution',
    Produits: 'Produits',
    Paypal: 'Payer avec PayPal',
    Montant: 'Montant de la contribution',
    AddProduct: 'Ajouter un produit',
  },
  Ventes: {
    title: 'Devenir Vendeur',
  },
  VentesList: {
    AddProduct: 'Ajouter un produit',
    ListProducts: 'Liste des produits',
    AddService: 'Ajouter un service',
    ListServices: 'Liste des Services',
  },
  AddProduct: {
    title: 'Ajouter un produit',
    Name: 'Nom',
    Description: 'Description',
    Quantite: 'Quantité',
    PrixUnitaire: 'Prix Unitaire',
    Devise: 'Devise',
    ProductExistError: 'Le produit est déjà été ajouté',
  },
  AddService: {
    title: 'Ajouter un service',
    AddOffre: 'Ajouter une offre',
    Offre: 'Offre',
    Zone: 'Zone à desservir',
    Category: 'Categorie',
    Conditions: 'Conditions',
    Capacites: 'Capacité',
    Calendrier: 'Calendrier',
    AddFormulas: 'Ajouter des formules',
    AddFormula: 'Ajouter une formule',
    FormulasAdded: 'Formules Ajoutées',
    Formula: 'Formule',
    TypePrix: 'Type de prix',
  },
  Achats: {
    title: 'Acheter',
  },
  BuyProduct: {
    title: 'Acheter un produit',
    Products: 'Produits',
    Quantity: 'Quantité',
    AddToCart: 'Ajouter au panier',
    Cart: 'Voir le panier',
    Stock: 'En stock',
    NoStock: 'Rupture de stock',
  },
  Cart: {
    title: 'Panier',
    items: 'Articles',
    tax: 'Taxes',
    Subtotal: 'Sous Total',
    Total: 'Total',
    Checkout: 'Procéder au paiement',
    EmptyCart: 'Panier vide',
  },
  Dropdown: {
    Select: 'Sélectionnez une devise',
    Category: 'Sélectionnez une catégorie',
    Product: ' Sélectionnez un produit',
    Event: 'Sélectionnez un  événement',
    Autre:'Autres',
    Zone:'Choisir une zone à desservir',
    Offre:'Choisir un offre',
    Province: 'Sélectionnez un province',
    Region: 'Sélectionnez une région',
    TypePrix : 'Sélectionnez un type de prix',
    Search: 'Chercher',
  },
  Products: {
    title: 'Liste des produits',
    EmptyList: 'Aucun produit ajouté',
  },
  Services: {
    title: 'Liste des Services',
    EmptyList: 'Aucune service ajoutée',
  },
  Settings: {
    title: 'Plus d’options',
  },
  SettingsList: {
    Settings: 'Paramètres',
    ContributionsList: 'Liste des contributions',
    InvitationsList: 'Liste des invitations',
    ProductOrderings: 'Mes commandes',
    ProductDelivering: 'Commandes à Livrer',
  },
  Setting: {
    title: 'Paramètres',
    Name: 'Votre nom',
    LanguageSetting: 'Paramètres de langue',
    ContactUs: 'Contactez-nous',
    Logout: 'Déconnexion',
    Email: 'Email',
    Phone: 'Téléphone',
    Version: 'Version',
    DeviseSetting: 'Paramètres de devise',
    CountrySetting: 'Paramètres de pays',
    TypeEvents: "Type d'événement",
  },
  LanguageList: {
    French: 'Français',
    English: 'Anglais',
  },
  Checkout: {
    title:'Procéder au paiement',
    Name: 'Nom',
    Email: 'Email',
    AdresseLine1: 'Adresse Ligne 1',
    AdresseLine2: 'Adresse Ligne 2',
    City: 'Ville',
    Province: 'Province',
    PostalCode: 'Code Postal',
    Phone: 'Téléphone',
    InfoPersonal: 'Informations personnelles',
    ShippingAddress: 'Adresse de livraison',
    Payment: 'Paiement',
    AmountToPay: 'Montant à payer',
    PlaceOrder: 'Passer la commande',
  },
  CategoryList: {
    Music: 'Musique et DJ',
    Photos: 'Photos et Appareil photo',
    Meals: 'Repas',
    Drink: 'Boissons',
    Dress: 'Robe',
    Transport: 'Transport',
  },
  StatusList: {
    Paid: 'Payée',
    BeingProcessed: 'En cours de traitement',
    ReadyToShip: 'Prête à expédier',
    Shipped: 'Expédiée',
    Livery: 'Livrée',
    Closed: 'Fermée',
  },
  RequestService: {
    title: 'Demander un service',
  },
  ProductOrderings: {
    title: 'Mes commandes',
    nbItems: "Nombre d'articles",
    TotalAmount: 'Montant total',
    DateDelivered: 'Date prévue de livraison',
    Status: 'Statut',
  },
  ProductDelivering: {
    title: 'Commandes à Livrer',
    Statut: 'Statut',
    DateDelivered:  'Date de livraison',
  },
  ContributionsList: {
    title: 'Liste des contributions',
    eventTitle: 'Evenement',
    userTitle: 'Donateur',
    natureTitle: 'Type de Contribution',
    montantTitle: 'Montant',
  },
  InvitationsList: {
    title: 'Liste des invitations',
    eventTitle: 'Evenement',
    userTitle: 'Invité',
    presenceTitle: 'Présence',
    nbrPersonTitle: 'Nombre de Personnes',
  },
  Order: {
    title: 'Commandes passées',
    paragraph: 'Les articles seront livrés dans les 72 prochaines heures',
  },
  ServiceOffer: {
    title: 'Service Offert',
    DateDelivered: 'Date de livraison',
  },
  TypeEvents: {
    title: "Type d'événement",
    EmptyList: "Aucun Type d'événement ajouté",
    List: "Liste Type d'événement",
    AddButtonText: "Ajouter un type d'événement",
  },
  AddTypeEvent: {
    title: "Ajouter Type d'événement",
    NameFr: "Nom en FR ",
    NameEn: "Nom en AN",
  },
  EditTypeEvent: {
    title: "Modifier Type d'événement",
  },
  OTPAuthScreen: {
    title: "Code de confirmation",
    paragraph: "Entrez un code de vérification pour vous connecter à l'application",
    confirmCode: "Code de confirmation",
    enterConfirmCode: "Entrer le Code de confirmation",
    CodeError: "Le code de confirmation est erroné. Ressayez",
  },
  DashboardList: {
    Dashboards: "Tableau de bord",
    Administrators: "Gestion des Administateurs",
    Users: "Gestion des Utilisateurs",
    Products: "Gestion des Produits",
  },
  Administrators:{
    AddButtonText: "Ajouter un administrateur",
    Name: "Prenoms et Nom",
    Phone: "Téléphone",
    Email: "Email",
    Modify: "Modifier un administrateur",
  },
  Dashboards:{
    NbrEvents: "Nombre d'événements",
    NbrInviteEvents: "Nombre d'invitations par événement",
    NbrDonationsEvents: "Nombre de contributions par événement",
    MntDonationsEvents: "Montant global des contributions par événement",
    NbrOrderDone: "Nombre de commandes effectuées",
    NbrOrderBeing: "Nombre de commandes en cours de livraion",
    NbrOrderDeliver: "Nombre de commandes livrées",
    NbrProducts: "Nombre de produits",
    NbrServices: "Nombre de services",
  },
  RatingScreen:{
    title: "Noter le Fournisseur",
    avis: "Écrire un avis",
  },
  PaymentList:{
    Paypal: "Pay pal",
    Card: "Carte Visa / MasterCard",
  },
  ResetPassword:{
    title: "Restaurer le mot de passe",
    Reset: "Restaurer",
  },
  TypePrix:{
    Unit: "Par unité",
    Person: "Par Personne",
  },
  WeekendList:{
    Lundi: "Lundi",
    Mardi: "Mardi",
    Mercredi: "Mercredi",
    Jeudi: "Jeudi",
    Vendredi: "Vendredi",
    Samedi: "Samedi",
    Dimanche: "Dimanche",
  },
  WeekSchedule:{
    StartTime:"Heure de début",
    EndTime:"Heure de fin",
    Capacity:"Capacité"
  },
};

export default translation;
