const translation = {
  Global: {
    Continue: 'Continue',
    Back: 'Retour',
    GoBackHome: "Retour a l'accueil",
    Modify: 'Modifier',
    from: 'De',
    to: 'From',
    Yes: 'Oui',
    No: 'Non',
    Search: 'Recherche',
    Create: 'Créer',
    Cancel: 'Annuler',
    Save: 'Enregister',
    None: 'Aucun',
    Nature: 'En nature',
    Argent: 'En argent',
    Add: 'Ajouter',
    Send: 'Envoyer',
    Message: 'Message',
    EmailErrorEmpty: "L'e-mail ne peut pas être vide.",
    PhoneErrorEmpty: "Le téléphone ne peut pas être vide.",
    NameErrorEmpty: "Le prénom et nom ne peut pas être vide.",
    PasswordErrorEmpty: "Le mot de passe ne peut pas être vide.",
    RetapePasswordErrorEmpty: "Retaper le mot de passe ne peut pas être vide.",
    DescriptionErrorEmpty: "Description ne peut pas être vide.",
    DeviseErrorEmpty: "Devise ne peut pas être vide.",
    ImageErrorEmpty: "Image ne peut pas être vide.",
    PrixUnitaireErrorEmpty: "Prix Unitaire ne peut pas être vide.",
    LocalisationErrorEmpty: "Emplacement ne peut pas être vide.",
    QuantiteErrorEmpty: "Quantité ne peut pas être vide.",
  },
  LoginScreen: {
    title: 'Connectez-vous',
    paragraph: 'Connectez-vous pour accéder à votre espace',
    Email: 'Email',
    Password: 'Mot de passe',
    Forgotpassword: 'Mot de passe oublié ?',
    Login: 'Se connecter',
    DontHaveAccount: 'Vous n’avez pas de compte ?',
    SignUp: "S'inscrire",
    LoginError: "Oups, L'e-mail et le mot de passe sont erronés",
  },
  RegisterScreen: {
    title: 'Créer un compte',
    paragraph: 'S’inscrire pour accéder à votre espace',
    Name: 'Prénoms et Nom',
    Email: 'Email',
    Phone: 'Téléphone',
    Password: 'Mot de passe',
    RetapePassword: 'Re-taper le mot de passe',
    Login: 'Se connecter',
    AlreadyHaveAccount: 'Vous avez déjà un compte ?',
    SignUp: "S'inscrire",
    EmailError: "Oups ! Nous avons besoin d'une adresse e-mail valide.",
    PhoneError: "Oups ! Nous avons besoin d'un numero de téléphone valide.",
    PasswordError: "S'inscrire",
    RetapePasswordError: "S'inscrire",
    PasswordNotConfirm: "Oups, les deux mots de passe ne correspondent pas.",
    AccountExists: "Cet email a déjà un compte",
  },
  Screens: {
    Home: 'Accueil',
    Events: 'Evénements',
    Invitations: 'Invitations',
    Contributions: 'Contributions',
    Settings: 'Plus',
  },
  HomeScreen: {
    title: 'Page d’accueil',
  },
  AccueilList: {
    Evenements: 'Evénements',
    Invitations: 'Invitations',
    Contributions: 'Contributions',
    Ventes: 'Vendre un produit/offrir un service',
    Achats: 'Acheter un produit/demander un service',
  },
  Events: {
    title: 'Evénements',
    EmptyList: 'Aucun événement pour le moment',
    AddButtonText: 'Créer un événement',
    addToCalendar: 'Ajouter au calendrier',
    Invite: 'Inviter',
    Invited: 'Invité',
    Maybe: 'Peut être',
    AmountDonation: 'Montant total',
    CloseDonation: 'Fermer la contribution'
  },
  AddEvent: {
    title: 'Créer un événement',
    Name: "Nom de l'événement",
    Description: 'Description',
    DateHeure: "Date et l'heure",
    DateDebut: 'Date de début',
    DateFin: 'Date de fin',
    Emplacement: 'Emplacement',
    CharacterCount: 'caractères',
    titleModify: 'Modifier un événement',
  },
  InvitationsContacts: {
    title: 'Invitez vos contacts',
    Share: 'Partage',
    Everyone: 'Tout le monde avec le lien',
    Limit: '+1 Limite',
    Nos: 'Pas de +1',
    Invite: 'Inviter un nouvel utilisateur',
    FromContacts: 'À partir des contacts',
    PhoneNumber: 'Numéro de téléphone',
    Invitee: 'Invité',
  },
  Invitations: {
    title: 'Invitations',
    EmptyList: 'Aucune invitation pour le moment',
  },
  InvitationsDetails: {
    title: 'Détails des invitations',
    Presence: "Présence à l'événement ?",
    nbrPersons: 'Nombre de personnes présentes',
    Adults: 'Adultes',
    KidsOver17: 'Enfants de 0 à 17 ans',
    KidsAge: "Âge de l'enfant"
  },
  Contributions: {
    title: 'Contributions',
    EmptyList: 'Aucune invitation au don pour le moment'
  },
  ContributionsDetails:{
    title: 'Faire un don',
    Contribution: 'Vous souhaitez contribuer à cet événement ?',
    Nature: 'Type de contribution',
    Produits: 'Produits',
    Paypal: 'Payer avec PayPal',
    Montant: 'Montant de la contribution',
    AddProduct: 'Ajouter un produit',
  },
  Ventes: {
    title: 'Vendre un produit/offrir un service',
  },
  VentesList:{
    AddProduct: 'Ajouter un produit',
    ListProducts:'Liste des produits',
    AddService: 'Ajouter un service',
    ListServices:'Liste des Services',
  },
  AddProduct:{
    title: 'Ajouter un produit',
    Name: 'Nom',
    Description: 'Description',
    Quantite: 'Quantité',
    PrixUnitaire: 'Prix Unitaire',
    Devise: 'Devise',
  },
  AddService:{
    title: 'Ajouter un service',
  },
  Achats: {
    title: 'Acheter un produit/demander un service',
  },
  AchatsList:{
    BuyProduct: 'Acheter un produit',
    RequestService: 'Demander un service',
  },
  BuyProduct:{
    title: 'Acheter un produit',
    Products: 'Produits',
    Quantity: 'Quantité',
    AddToCart: 'Ajouter au panier',
    Cart: 'Voir le panier'
  },
  Cart:{
    title: 'Panier',
  },
  Dropdown: {
    Select: 'Sélectionnez une devise',
  },
  Products:{
    title: 'Liste des produits',
  },
  Settings: {
    title: 'Plus d’options',
  },
  SettingsList: {
    Settings: 'Paramètres',
    ContributionsList: 'Liste des contributions',
    InvitationsList: 'Liste des invitations',
    ProductOrderings: 'Commandes de produits',
    ProductDelivering: 'Livraisons de produits',
  },
  Setting: {
    title: 'Paramètres',
    Name: 'Votre nom',
    LanguageSetting:'Paramètres de langue',
    ContactUs:'Contactez-nous',
    Logout:'Déconnexion',
    Email:'Email',
    Phone:'Téléphone',
    Version:'Version',
  },
  LanguageList: {
    French: 'Français',
    English: 'Anglais',
  },
  Checkout: {
    Name: 'Nom',
    Email: 'Email',
    AdresseLine1: 'Adresse Ligne 1',
    AdresseLine2: 'Adresse Ligne 2',
    City: 'Ville',
    Province: 'Province',
    PostalCode: 'Code Postal',
    Phone: 'Téléphone',
  },
}

export default translation
